### ISSUE TITLE
文档关于配置项 picBed.transformer 的问题

### ISSUE THREAD

**Issue by upupming** [PicGo/PicGo-Core-Doc#1]
`transformer` 配置项根据代码是在 `picBed` 对象之下：

![image](https://user-images.githubusercontent.com/24741764/85224153-bcdcbc00-b3fa-11ea-8deb-2b54612b6ea2.png)

但是文档中写的 transform 配置并未位于 `picBed` 之下：

![image](https://user-images.githubusercontent.com/24741764/85224168-e72e7980-b3fa-11ea-9191-6343481691d9.png)

不知道我的理解是否正确，现在好像只有 `path` 一种 transformer，在 awesome-picgo 里面也没有看到新的 transformer，是否应该修改文档呢？

**Comment by upupming** [comment]
另外，`#picgo-plugin-*` 部分也应该放在 `picgoPlugins` 之下：

![image](https://user-images.githubusercontent.com/24741764/85224351-5fe20580-b3fc-11ea-961c-55910b45a7a3.png)

**Comment by Molunerfinn** [comment]
不是的。
picBed下的`transformer`只是用来告知当前的`transformer`是啥，但是`transformer`本身可能有配置。比如有一个图片压缩的`transformer`叫`xxx`需要配置清晰度，那清晰度这个配置就是在`transformer.xxx`下。

`picgoPlugins`是用来查看插件是否被启用的。`true`是启用，`false`是禁用。这个不需要插件关心，是picgo自带的能力，插件自身的配置依然是放在 `picgo-plugin-*` 下。
